# Generated by Django 2.2.5 on 2021-05-05 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20210505_1802'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rerservation',
            new_name='Reservation',
        ),
    ]
